### ISSUE TITLE
Missing dependency on huggingface_hub

### ISSUE THREAD

**Issue by nicholasdehnen** [octanove/shiba#11]
Using shiba-model==0.1.1, python 3.11.5, SHIBA installed using `pip install shiba-model`.
When trying to run the sample code provided, I get the following exception:

```
Traceback (most recent call last):
  File "/home/user/Code/project/model/test.py", line 7, in <module>
    from shiba import Shiba, CodepointTokenizer, get_pretrained_from_hub
  File "/home/user/mambaforge/envs/project/lib/python3.11/site-packages/shiba/__init__.py", line 1, in <module>
    from shiba.model import Shiba, ShibaForAutoregressiveLanguageModeling, ShibaForClassification, ShibaForSequenceLabeling, \
  File "/home/user/mambaforge/envs/project/lib/python3.11/site-packages/shiba/model.py", line 10, in <module>
    from huggingface_hub import hf_hub_url
ModuleNotFoundError: No module named 'huggingface_hub'
```

Installing huggingface_hub with `pip install huggingface_hub` fixes this.
As such I think that huggingface_hub should either be made optional (only for get_pretrained_from_hub), or added to the pypi package as dependency.

**Comment by Mindful** [comment]
@nicholasdehnen whoops, I totally forgot to add the HF hub dependency to the requirements.txt when I made some changes a little while back. Good catch, thank you. 

You're welcome to open a PR for this if you'd like, otherwise I'll add it to the dependencies sometime in the next few days. I think it actually has to be an older version of `huggingface_hub` for the download code to work properly, though I need to double check that. 

edit: yeah I think the code runs on version ` 0.0.8`

**Comment by nicholasdehnen** [comment]
I think it worked fine for me with the newest version too. Thank you so much for the quick fix!
